version: '3'
services:
  surreybook:
    image: surreybook
    networks:
      - surreybook_network
    ports:
      - "8080:8080"
    depends_on:
      - mysqlcontainer

  mysqlcontainer:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Samar1213134
      - MYSQL_DATABASE=Surreybook
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    networks:
      - surreybook_network
    ports:
      - "3308:3306"

networks:
  surreybook_network:
    driver: bridge
